name: main build

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - main/Chapter*.md
      - main/image/**
      - main/config-pdf.yaml
      - main/config-epub.yaml
      - listing.tex
      - .github/workflows/pandoc.yaml
      - .github/workflows/main.yaml

jobs:
  build:
    uses: ./.github/workflows/pandoc.yaml
    with:
      working-directory: ./main
